import { signIn, useSession } from 'next-auth/react';
import Head from 'next/head';
import { Layout } from '~/components/layout';
import { type ReactElement } from 'react';

function LoggedIn() {
    return (
        <>
            <Head>
                <title>Dashboard</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="absolute right-0 top-0 flex h-full flex-col">
                <div></div>
            </main>
        </>
    );
}

function LoggedOut() {
    return (
        <>
            <Head>
                <title>Almanac</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="absolute right-0 top-0 flex h-full flex-col">
                <div>
                    <button
                        className="rounded-m border-2 border-black px-2 py-1 font-semibold"
                        onClick={() =>
                            void signIn('auth0', { callbackUrl: '/main' })
                        }
                    >
                        Sign in
                    </button>
                </div>
            </main>
        </>
    );
}

Home.getLayout = function getLayout(page: ReactElement) {
    return <Layout>{page}</Layout>;
};

export default function Home() {
    const { data: sessionData } = useSession();

    return sessionData ? <LoggedIn /> : <LoggedOut />;
}
